### ISSUE TITLE
model-method showCars() 

### ISSUE THREAD

**Issue by Dachgruber** [baschi29/streetlife#1]
ich brauche eine Methode showCars() (oder so ähnlich), welche eine Liste an allen verfügbaren Autos zurückgibt.

Die Liste sollte eine Form von möglichen Auto-Bauplänen geben (langsamer Traktor, schneller Fiat, etc), sodass der Benutzer aus diesen Vorlagen wählen kann und eine Kopie für das Modell hinzufügen kann

**Comment by baschi29** [comment]
Ich denke mal, ich werd das so machen, dass die methode showList(object) ist und wenn man car übergibt kommen alle cars
