### ISSUE TITLE
Give objects x and y Dimensions

### ISSUE THREAD

**Issue by baschi29** [baschi29/streetlife#21]
Not only should they have dimension, but also check collisions respecting those dimensions

**Comment by baschi29** [comment]
Already started with [b4aeb596e70f0b8c4af648cd022ba20511b6daba](https://github.com/baschi29/streetlife/commit/b4aeb596e70f0b8c4af648cd022ba20511b6daba)

See yExtension of StreetObjects

**Comment by Dachgruber** [comment]
Every car has an img - a BufferdImage-object, which is basically the representation on the gui and the size of the car the user actually sees.
Could work with car.getImg().getHeight() and car.getImg().getWidth() so that the size of the car actually corresponds with the size of the display

**Comment by baschi29** [comment]
I think the size of the car in the model doesn't necessarily have to correspond to the size of the image as view and model should be independent from each other, but I will look into that
