### ISSUE TITLE
Fix GUI Linux compability

### ISSUE THREAD

**Issue by baschi29** [baschi29/streetlife#24]
On Linux, all popup dialogs are blank.

Maybe caused by this: https://stackoverflow.com/questions/4740183/java-ubuntu-linux-swing-blank-window

See also: https://www.cs.fsu.edu/~jtbauer/cis3931/tutorial/ui/swing/threads.html
https://stackoverflow.com/questions/38323372/java-gui-is-blank
https://www.reddit.com/r/swaywm/comments/qu182b/having_weird_problems_trying_to_get_intellij_idea/

https://stackoverflow.com/questions/2484615/what-is-the-event-dispatching-thread

Probably related to this:
https://stackoverflow.com/questions/14486147/java-web-start-application-shows-empty-window-on-xmonad
https://github.com/Smithay/smithay/issues/389

**Comment by Dachgruber** [comment]
changed JDialog.type to .NORMAL, should fix this issue
