### ISSUE TITLE
New objects should  be added on new, unoccupied position

### ISSUE THREAD

**Issue by baschi29** [baschi29/streetlife#3]

**Comment by Dachgruber** [comment]
still not working for me, cars start ontop of each other

**Comment by Dachgruber** [comment]
![grafik](https://user-images.githubusercontent.com/52976259/152135974-530ea46d-5078-4bdc-9452-80e3430e496f.png)
maybe there should be random lane selection, as well as a method that cancels the addition when cars overlap

**Comment by baschi29** [comment]
if you look at the x position they are indeed not on top of each other, but I will fix this with implementation of #21
