### ISSUE TITLE
Remove BufferedImages variables from all model classes

### ISSUE THREAD

**Issue by Dachgruber** [baschi29/streetlife#40]
save method in controller class tries to save components, that are not serializable. Therefore the save function does not work atm

**Comment by baschi29** [comment]
BufferedImages aren't serializable. I would recommend moving everything related to visualization to the view including the bufferedimage.

Alternative: implement serializable wrapper method: https://stackoverflow.com/questions/15058663/how-to-serialize-an-object-that-includes-bufferedimages

**Comment by Dachgruber** [comment]
should be done now
