### ISSUE TITLE
Deletion ComboBox options are not updated when an object gets removed by the model

### ISSUE THREAD

**Issue by baschi29** [baschi29/streetlife#6]
If for example a frog gets removed from the model, it is still shown as an option for deletion in the deletion Combo Box

Frog gets removed:
![grafik](https://user-images.githubusercontent.com/55055342/151020516-1fc61e97-d2ea-431d-a4a0-bddfe368abf2.png)

Frog still present in ComboBox:
![grafik](https://user-images.githubusercontent.com/55055342/151020712-dfbbe20b-25c0-4b8a-a6e9-c2b51d35e377.png)

**Comment by Dachgruber** [comment]
fixed
