### ISSUE TITLE
Error-Popup-Window

### ISSUE THREAD

**Issue by Dachgruber** [baschi29/streetlife#7]
We need a Popup for displaying user-friendly error messages

**Comment by baschi29** [comment]
Not working for me, ex. when adding more than 10 frogs simultaneously

**Comment by Dachgruber** [comment]
> Not working for me, ex. when adding more than 10 frogs simultaneously

adding many frogs should not throw any exceptions, Could confirm error dialog working while throwing errors manuelly

**Comment by baschi29** [comment]
Is implemented, specific problem tracked/in #24
