### ISSUE TITLE
Lane display

### ISSUE THREAD

**Issue by Dachgruber** [baschi29/streetlife#8]
We need some sort of solution for displaying different lanes (painting onto DrawingSpacePanel), needs to be custom for different street sizes

**Comment by baschi29** [comment]
Should be now possible. All lanes are stored as StreetObjects inside the model State. Also it is possible to get the first lane via model.getFirstLane() and the next lanes vie lane.getTopLane().

The middle of the lane is the y Position: lane.getY()

The overall width of the lane can get obtained via lane.getYExtension()

**Comment by Dachgruber** [comment]
Should be implemented with c0ed28f1cbbf1d2bdb1da66dca6d09415f52dbe9

**Comment by baschi29** [comment]
https://github.com/baschi29/streetlife/commit/c0ed28f1cbbf1d2bdb1da66dca6d09415f52dbe9 does improve this, the lane at the top now has a nice drawn through line, but it still draws only 2 lanes no matter the actual lane size

![grafik](https://user-images.githubusercontent.com/55055342/152139657-a4306d8d-d3ba-44bc-aff5-e0a3b8a9dd74.png)
